site_name: Galaxy Policies
site_url: !ENV [MKDOCS_SITE_URL, "https://policy.galaxy.casa"]
repo_name: !ENV [MKDOCS_REPO_NAME, "GalaxyRoblox/Policies"]
repo_url: !ENV [MKDOCS_REPO_URL, "https://github.com/GalaxyRoblox/Policies"]
edit_uri: !ENV [MKDOCS_EDIT_URI, "edit/main/docs"]
copyright: Copyright &copy; {year}, GalaxyRoblox
docs_dir: docs

site_author: GalaxyRoblox
site_description: This website contains some of the policies used by the Galaxy staff team.

nav:
  - index.md
  - Discord Moderation Guidelines: moderation.md

hooks:
  - hooks/config.py
  - hooks/slug_replacer.py

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_GIT_REVISION_DATE, true]
      enable_creation_date: true
      fallback_to_build_date: true
      type: timeago
  - group:
      enabled: !ENV CI
      plugins:
        - social
        - privacy
        - minify:
            minify_html: true
            htmlmin_opts:
              remove_comments: true

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    annotation: material/chevron-right-circle-outline
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  logo: img/galaxy.png
  favicon: img/galaxy.png

extra:
  social:
    - icon: simple/roblox
      link: https://www.roblox.com/games/12426862174
      name: Play Galaxy on Roblox!
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/robloxgalaxy
      name: Join the official Galaxy Discord server!
    - icon: simple/miraheze
      link: https://wiki.galaxy.casa
      name: Galaxypedia - The official Galaxy wiki!

watch:
  - includes
  - hooks
