name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Analysing Markdown files with markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: "**/*.md"
