name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Analysing Markdown files with markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"

  ruff:
    name: Lint Python Files with Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync && echo "UV_NO_SYNC=true" >> $GITHUB_ENV

      - name: Analysing Python code with ruff
        run: uv run ruff check $(git ls-files '*.py')

  basedpyright:
    name: Lint Python Files with basedpyright
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync && echo "UV_NO_SYNC=true" >> $GITHUB_ENV

      - name: Analysing Python code with basedpyright
        run: uv run basedpyright $(git ls-files '*.py')
